language: python
sudo: false
cache: false
python:
- '3.5'
os:
- linux
env:
  global: PYTHONUNBUFFERED=yes
  matrix:
  - TOXENV=3.5-django2.0
  - TOXENV=3.5-django1.11
  - TOXENV=2.7-django1.11
  - TOXENV=flake8
  - TOXENV=flakeplus
  - TOXENV=apicheck
  - TOXENV=pydocstyle
  - TOXENV=cov
install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
- ".tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml"
- ".tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV"
deploy:
  provider: pypi
  on:
    tags: true
  user:
    secure: fySYiFqmqu7q7pIWjmjNV7lxjaiVytPxJSiy+bMGofMfiT6fXxm4pGuQtcougyoMlUFtkZdW5sWDTWz0jEhJ2ACpxBYIOqyouO9yXrCOcRaW134XmQBczJu2GrsGADVH0euH7SVs14nZYFASUPm0StXCT4z8wvk9pVq5Or53EzS8poyBPLBwdz60rzTOLcVYK/soym/n9vdvo+eaYljeuG8Cct+KIPHOz7Ss882gLY7Mq5cZVctZh0tLw9UUbWaLQ4OxhXFKxhuLUFoh92fPzj2eyLTMfu1YU7FsY0A1r4Jki2KI6wTk0GSy7Yl/4UZSvEmxzDN+gJt/ypqjD7LIonjMEe5ThwKA81sLtGAFxJm/181IKvTFrPRoXnBq2YmLvseOvd6/Ci6euAEFdpZwCLOJJ4E08jTn7UnHhS8t0bokJiG/3opTLv3GbKkiq7aQQs5ui7UOJY2oyWxqUYy9WTwSwInx06moaRIgjj8yajjabqY8U3cU2lYrKdiV6IXJEd0WIhkmtt/IAwn3wkIRk7MDHZDJkCsgHOpxSenZkz96OsIsj8Hw+i7jq6T3cdPBOXK2HjrSsleHqnxRbBSOSFCKidaEcf+GSq6K+9yoj9tGww4D6w2cwUuPu4kQUhXjvMwn66xzqZyPeTSjvx0fkUU1Uyxz+4rTkE91lAaoDt4=
  password:
    secure: dlwvPNSpAxNz7Mg4/7Ff7fhAGbkhiVTna0tKkwM4oSMENijpKyvtaaPyqYUIiUROaT7byAHbgb0sln3JQCmpuDdVLTm+qq6J9VDmRJ5+mXFqj8f8Ri+BnGfHw8+JzSu0b/2qRIGpgToYx04vfzpCp9raCj6oLqsm0uSf0bn83XAsO0PKsdUsvZ5mZGHhM3VgpIHtTNswmfiPtWnEX6hNN5tbZJWZ7/sh9OPGIq8eRjRjDHqF9yOi7Ps6/X7ZKqrXvo6c2mIiyjjh9CbUkPqlB08ajUFe/XMecku0OALocVWM6g0RnqhCDPd/a7AeIg825wWPMBQVdvlTUyUdcnIAUJrRnz8iCVQz3ZCuSUCS3NQUF3MKqWI3wvYNt+wS1DGNiNB0MVHMLxJCVCuSptWTPfIyW2Pgy70HObR1LG0xJADNtGvnvygUyOOeNbg3d5+pRNMVmqJan1sTWTVuH467Y0s3f+37NrGK04w09lZglm6cwwhC0avCepOxK1SGU6fkNWE039wbO42GxbByhsNqYhfsfmvFpvyyPpTycHxPyPD+RpLgk+uXnOg8GwiQsjr8WQGbVC7WP0RQegEYIgLC6kDDzmQLK8Q/Guz9SAW3cMm6iWDKi5FjFru1ItJSua97HR6sYWFIwLwRGqa6jTLqzqea96IX8PLeSFRytjvuxgI=
